name: dart_native_sample
description: Dart2Native sample web server app.
version: 1.0.0
homepage: https://suresh.dev
author: Suresh G

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  resource: ^2.1.6
  path: ^1.6.4
  basic_utils: ^2.3.7

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
