name: dart_native_sample
description: Dart2Native sample web server app.
version: 1.0.0
homepage: https://suresh.dev
author: Suresh G

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  quiver: ^2.1.3
  basics: ^0.4.0+1
  retry: ^3.0.0+1
  path: ^1.7.0
  collection: ^1.14.12
  http: ^0.12.1
  crypto: ^2.1.5
  resource: ^2.1.6
  basic_utils: ^2.5.3
  petitparser: ^3.0.2
  #  pem: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.5
  mockito: ^4.1.1
