name: dart_native_sample
description: Dart2Native sample web server app.
version: 1.0.0
homepage: https://suresh.dev
author: Suresh G

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  quiver: ^2.1.3
  basics: ^0.4.0+1
  retry: ^3.0.1
  path: ^1.7.0
  collection: ^1.14.12
  http: ^0.12.2
  crypto: ^2.1.5
  resource: ^2.1.7
  basic_utils: ^2.6.2
  petitparser: ^3.1.0
  rsocket: ^0.1.0
  puppeteer: ^1.18.0
  args: ^1.6.0
  #  pem: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  mockito: ^4.1.1
