name: Dart Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 1 * 0

jobs:
  jit:
    name: DartVM (JIT)
    runs-on: ubuntu-latest

    container:
      image: google/dart:dev

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Run tests
        run: pub run test

  aot:
    name: Dart2Native (AOT)
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        channel:
          - dev
        include:
          - os: ubuntu-latest
            bin-name: test-server-linux
          - os: macos-latest
            bin-name: test-server-mac
          - os: windows-latest
            bin-name: test-server-windows.exe
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dart SDK ${{matrix.channel}} on ${{matrix.os}}
        uses: cedx/setup-dart@v2
        with:
          release-channel: ${{matrix.channel}}

      - name: Fetch Dependencies
        run: pub get

      - name: Dart Format
        run: dartfmt --set-exit-if-changed .

      - name: Dart Analyzer
        run: dartanalyzer --fatal-warnings .

      - name: Test
        run: pub run test --reporter expanded

      # - name: Generate Coverage
      #   run: pub run test_coverage --no-badge

      # - name: Upload Coverage
      # uses: codecov/codecov-action@v1.0.7

      # - name: Cache Dart packages
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.pub-cache
      #     key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-dart-

      - name: Dart2Native Build
        run: |
          dart --version
          dart2native bin/main.dart -v -DdefaultPort=8445 -o ${{ matrix.bin-name }}
          echo "The binary file name is ${{ matrix.bin-name }}"

      - name: Uploading ${{ matrix.bin-name }}
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.bin-name }}
          path: |
            ${{ matrix.bin-name }}
          if-no-files-found: error

  execute:
    name: Run Native Binaries
    needs: aot
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            bin-name: test-server-linux
          - os: macos-latest
            bin-name: test-server-mac
          - os: windows-latest
            bin-name: test-server-windows.exe

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.bin-name }}

      - name: Executing on (${{ matrix.os }})
        if: startsWith(matrix.os, 'windows')
        run: |
          .\${{ matrix.file-name }} -s

      - name: Executing on (${{ matrix.os }})
        if: !startsWith(matrix.os, 'windows')
        run: |
          chmod +x ${{ matrix.file-name }}
          ./${{ matrix.file-name }} -s
