name: Dart2Native Build

# Trigger setup
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

# Build Jobs
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
